=== wiewioraseb/RoboticArm/Robotic Arm/src/armPosition.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT main (arm+,x , y, active_joints)>
<!ELEMENT arm (angle)>
<!ELEMENT main (#PCDATA)>
<!ELEMENT arm (#PCDATA)>
<!ELEMENT angle (#PCDATA)>
<!ELEMENT x (#PCDATA)>
<!ELEMENT y (#PCDATA)>

=== wiewioraseb/RoboticArm/Robotic Arm/src/armPosition.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE main SYSTEM "armPosition.dtd">
<main>
  <arm>
    <angle>90</angle>
  </arm>
  <arm>
    <angle>90</angle>
  </arm>
  <arm>
    <angle>90</angle>
  </arm>
  <x>100</x>
  <y>150</y>
  <active_joints>3</active_joints>
</main>
